#pragma once

typedef enum ENUM_OPC {
    OPC_NOP             =   0,

    OPC_MOV_P_V         =   10,
    OPC_MOV_P_P         =   11,
    OPC_MOV_P_PP        =   12,
    OPC_MOV_PP_V        =   13,
    OPC_MOV_PP_P        =   14,
    OPC_MOV_PP_PP       =   15,

    OPC_JMP_V           =   20,
    OPC_JMP_P           =   21,
    OPC_JMP_PP          =   22,

    OPC_JEZ_P_V         =   30,
    OPC_JEZ_P_P         =   31,
    OPC_JEZ_P_PP        =   32,
    OPC_JEZ_PP_V        =   33,
    OPC_JEZ_PP_P        =   34,
    OPC_JEZ_PP_PP       =   35,

    OPC_JGZ_P_V         =   40,
    OPC_JGZ_P_P         =   41,
    OPC_JGZ_P_PP        =   42,
    OPC_JGZ_PP_V        =   43,
    OPC_JGZ_PP_P        =   44,
    OPC_JGZ_PP_PP       =   45,

    OPC_JGZ_P_V         =   50,
    OPC_JGZ_P_P         =   51,
    OPC_JGZ_P_PP        =   52,
    OPC_JGZ_PP_V        =   53,
    OPC_JGZ_PP_P        =   54,
    OPC_JGZ_PP_PP       =   55,

    OPC_SYS_P           =   60,
    OPC_SYS_PP          =   61,

    OPC_NEG_P           =   70,
    OPC_NGE_PP          =   71,

    OPC_ABS_P           =   80,
    OPC_ABS_PP          =   81,

    OPC_INC_P           =   90,
    OPC_INC_PP          =   91,

    OPC_DEC_P           =   100,
    OPC_DEC_PP          =   101,

    OPC_ADD_P_V         =   110,
    OPC_ADD_P_P         =   111,
    OPC_ADD_P_PP        =   112,
    OPC_ADD_PP_V        =   113,
    OPC_ADD_PP_P        =   114,
    OPC_ADD_PP_PP       =   115,
    OPC_ADD_P_V_P       =   116,
    OPC_ADD_P_P_P       =   117,
    OPC_ADD_P_PP_P      =   118,
    OPC_ADD_PP_V_P      =   119,
    OPC_ADD_PP_P_P      =   120,
    OPC_ADD_PP_PP_P     =   121,
    OPC_ADD_P_V_PP      =   122,
    OPC_ADD_P_P_PP      =   123,
    OPC_ADD_P_PP_PP     =   124,
    OPC_ADD_PP_V_PP     =   125,
    OPC_ADD_PP_P_PP     =   126,
    OPC_ADD_PP_PP_PP    =   127,

    OPC_DIV_P_V         =   130,
    OPC_DIV_P_P         =   131,
    OPC_DIV_P_PP        =   132,
    OPC_DIV_PP_V        =   133,
    OPC_DIV_PP_P        =   134,
    OPC_DIV_PP_PP       =   135,
    OPC_DIV_P_V_P       =   136,
    OPC_DIV_P_P_P       =   137,
    OPC_DIV_P_PP_P      =   138,
    OPC_DIV_PP_V_P      =   139,
    OPC_DIV_PP_P_P      =   140,
    OPC_DIV_PP_PP_P     =   141,
    OPC_DIV_P_V_PP      =   142,
    OPC_DIV_P_P_PP      =   143,
    OPC_DIV_P_PP_PP     =   144,
    OPC_DIV_PP_V_PP     =   145,
    OPC_DIV_PP_P_PP     =   146,
    OPC_DIV_PP_PP_PP    =   147,

    OPC_MUL_P_V         =   150,
    OPC_MUL_P_P         =   151,
    OPC_MUL_P_PP        =   152,
    OPC_MUL_PP_V        =   153,
    OPC_MUL_PP_P        =   154,
    OPC_MUL_PP_PP       =   155,

    OPC_SHL_P_V         =   160,
    OPC_SHL_P_P         =   161,
    OPC_SHL_P_PP        =   162,
    OPC_SHL_PP_V        =   163,
    OPC_SHL_PP_P        =   164,
    OPC_SHL_PP_PP       =   165,

    OPC_SHR_P_V         =   170,
    OPC_SHR_P_P         =   171,
    OPC_SHR_P_PP        =   172,
    OPC_SHR_PP_V        =   177,
    OPC_SHR_PP_P        =   174,
    OPC_SHR_PP_PP       =   175,

    OPC_HLT_V           =   180,
    OPC_HLT_P           =   181,
    OPC_HLT_PP          =   182,
} ENUM_OPC;
